### ISSUE TITLE
Override Admin Login Page

### ISSUE THREAD

**Issue by payton** [payton/django-siwe-auth#16]
Currently, the Django admin login page defaults to password authentication. This is no longer plausible for key-pair authentication.

Issue identified in https://github.com/payton/django-siwe-auth/issues/15

**Comment by pconerly** [comment]
This is also a duplicate of https://github.com/payton/django-siwe-auth/issues/7

But the link is valuable https://docs.djangoproject.com/en/dev/ref/contrib/admin/#root-and-login-templates
