### ISSUE TITLE
examples/notepad/frontend doesn't build

### ISSUE THREAD

**Issue by pconerly** [payton/django-siwe-auth#17]
I noticed that when running `yarn dev` in `examples/notepad/frontend` it doesn't run, because the `../siwe` directory is missing.  I also noticed that `siwe` isn't added to packages.

Is this intentional? I was guessing that you have a local copy of `siwe` in `examples/notepad/siwe`.

**Comment by payton** [comment]
Not intentional, @pconerly ! I wrote the initial version of siwe-py and was making this project at the same time. Thanks for catching it.
