### ISSUE TITLE
Error on goerli test network

### ISSUE THREAD

**Issue by pconerly** [payton/django-siwe-auth#26]
I'm getting an error when I point at the goerli test network, which uses POA.

It's the same error as in this SO: https://stackoverflow.com/questions/70812529/the-field-extradata-is-97-bytes-but-should-be-32-it-is-quite-likely-that-you-a

And I think the fix would be the same, but I don't know (and haven't extensively tested) if `geth_poa_middleware` still works with the proof of work networks

**Comment by pconerly** [comment]
This bug also happens on ropsten

**Comment by payton** [comment]
Resolved in #29 
Thanks @pconerly
