### ISSUE TITLE
Include migrations in packaged `siwe_auth`

### ISSUE THREAD

**Issue by pconerly** [payton/django-siwe-auth#27]
So, in other django plugins the migrations are generated and included in the source code.

such as:
https://github.com/django/django/tree/main/django/contrib/auth/migrations

Not having it means that when I deploy, I need to run `./manage.py makemigrations` and then `./manage.py migrate`. The migration files I make in `makemigrations` are also transient, since they're just for an installed dependency.

**Comment by pconerly** [comment]
And I'm feeling like I should go back on this PR https://github.com/payton/django-siwe-auth/pull/22
The problem wasn't that migrations were included in `example/notepad`, the issue is that they were missing from `siwe_auth`

**Comment by payton** [comment]
Resolved in #28
